### ISSUE TITLE
Change API to accept names without the path and the lib prefix

### ISSUE THREAD

**Issue by eyalroz** [martin-olivier/dylib#18]
At the moment, one has to specify either the full path of a dynamic library, or the full path sans the extension (and even in that case, you need to incant the magic spell of `mylib::extension`). In particular, this means that it is up to library user to construct the path correctly, and to make sure that on some OSes, `lib` is prepended, while on others it is not. Also, the user has to pass a concrete path, something else which is prone to change when porting.

Instead, or at least, in addition to this API, the user code should be able to _not be aware_ of these issues, and just be able to get the library using its basic name (and perhaps a path).

Ideally, I would like to be able to write
```
auto foo_lib = dylib::load("foo");
```
and for `load()` to do the following:

* Decide whether to use `libfoo` or `foo` as the basename.
* Decide which extension to append
* Search the appropriate sequence of directories for the shared library file (e.g. on Linux current dir, then `LD_LIBRARY_SEARCH_PATH`)

alternatively, and if we're stuck with the current API, I would expect this to work:
```
auto foo_lib_path = dylib::build_path("foo");
dylib foo_lib = dylib::lib(foo_lib_path);
```
and the above snippets could have variants specifying the location, e.g.
```
auto foo_lib = dylib::with_search_paths(dylib::search_recursively, "/some/path1", "/some/path2").load("foo");
```
for the first option or
```
auto foo_lib_path = dylib::with_search_paths(dylib::search_recursively,  "/some/path1", "/some/path2").build_path("foo");
dylib foo_lib = dylib::lib(foo_lib_path);
```
for the second option.

**Comment by martin-olivier** [comment]
I was thinking of doing it this way :

```c++
class dylib {
    static constexpr auto library_path = "";
    static constexpr auto current_path = "./";

    static constexpr bool find_recursively = true;
    static constexpr bool find_locally = false;

    dylib(const std::string path, const std::string name, bool find_recursively = false);
}
```

Example :

```c++
// foo will became :
// libfoo.so on linux
// libfoo.dylib on macOS
// foo.dll on windows

// try to find foo recursively from the current path :

dylib lib(dylib::current_path, "foo", dylib::find_recursively);

// try to find foo from the os library path :

dylib lib(dylib::library_path, "foo");
```

**Comment by eyalroz** [comment]
`current_path` <- 

```
static constexpr auto current_path = "";
static constexpr auto library_path = "";
```
These are confusing.  Also. `./` is a Unix convention.

```
static constexpr bool find_recursively = true;
static constexpr bool find_locally = false;
```
looks like an `enum : bool { ... }` to me... also "locally" is not the opposite of "recursively".

Also, you can't "find recursively"... you can "search recursively", or "recurse subdirectories".

Again, I would consider using a proxy object which receives search information, and returns something which has a `search()` or `load()` method that only takes the library name. That  proxy object may be used repeatedly.

**Comment by martin-olivier** [comment]
> These are confusing. Also. ./ is a Unix convention.

The windows API support both `/` and `\`

I have made changes to make the dylib class RAII compliant and add the cross-platform prefix support.
Do not hesitate to review thoses changes https://github.com/martin-olivier/dylib/pull/34

> Again, I would consider using a proxy object which receives search information, and returns something which has a search() or load() method that only takes the library name. That proxy object may be used repeatedly.

I think i will add in a second time a class `dylib::search_paths` to do this job.
The main issue is that this lib is in c++11 and we don't have access to `std::filesystem` to make cross-platform recursive search

**Comment by eyalroz** [comment]
> The main issue is that this lib is in c++11 and we don't have access to std::filesystem to make cross-platform recursive search

Remember you could always have conditionally-compiled code, so that some features are only available in C++14 and onwards.

**Comment by martin-olivier** [comment]
Done in https://github.com/martin-olivier/dylib/pull/34
