### ISSUE TITLE
Why construct dummy dylib's?

### ISSUE THREAD

**Issue by eyalroz** [martin-olivier/dylib#30]
The dylib class [has a default ctor](https://github.com/martin-olivier/dylib/blob/e06af0f3b5c780d35659c54ea3f7aad9ae008494/include/dylib.hpp#L96). Why? What is the use of a "dummy", empty, dylib? Should you not follow the [RAII](https://en.cppreference.com/w/cpp/language/raii) paradigm, and let construct correspond to opening a library, and destruction to closing it?

**Comment by martin-olivier** [comment]
You are right, i need to remove the `default ctor` and the `close` function.
In your opinion, should i keep the `open` function for "reusable" purposes or get rid of it ?

**Comment by eyalroz** [comment]
> In your opinion, should i keep the open function for "reusable" purposes or get rid of it ?

What's useful about an existing instance, that remains useful after you've closed one library in order to open another?

**Comment by martin-olivier** [comment]
I have originaly made `dylib` following `std::ofstream` syntax (default ctor, open, close, ...).
But i saw the main reason it was designed like that (not RAII compliant) is because the dtor process may fail, witch is not the case with `dylib`

> What's useful about an existing instance, that remains useful after you've closed one library in order to open another?

Perhaps the user wants to open a lib, check if an existing symbol is here and if its not the case open another lib within the same instance

**Comment by eyalroz** [comment]
Remember that streams are a very very old C++ facility, and these days would likely have been designed somewhat differently.

> Perhaps the user wants to open a lib, check if an existing symbol is here and if its not the case open another lib within the same instance

Why would the user want to use the same instance? How does that help them?
```
auto my_lib = dylib::open("foo");
if (not my_lib.contains("my_symbol")) {
    my_lib = dylob::open("bar");
}
```

**Comment by martin-olivier** [comment]
Done in https://github.com/martin-olivier/dylib/pull/34
