### ISSUE TITLE
Better check for symbol presence than NULL comparison

### ISSUE THREAD

**Issue by eyalroz** [martin-olivier/dylib#33]
At the moment, there are two ways to check whether a library contains a symbol: Trying to `get_xxxx` it - which may throw, and requires the type; or `get_symbol()`, which doesn't throw, and may return NULL.

I'm not sure the user should even have to know about NULL in order to check for symbol presence. 

There are different ways to approach this. One would be returning an optional; another - a `contains()` or `has()` method which returns a boolean.

**Comment by martin-olivier** [comment]
> I'm not sure the user should even have to know about NULL in order to check for symbol presence.

`get_symbol()` is a private member function

> There are different ways to approach this. One would be returning an optional; another - a contains() or has() method which returns a boolean.

i made `has_symbol()` function is order to do that

**Comment by eyalroz** [comment]
Sorry, I missed that.
