### ISSUE TITLE
Add a named constant for not using OS decorations

### ISSUE THREAD

**Issue by eyalroz** [martin-olivier/dylib#51]
Instead of saying:
```
dylib lib("foo.lib", false);
```
I should be able to say:
```
dylib lib("foo.lib", dylib::no_decorations);
```
or
```
dylib lib("foo.lib", dylib::no_os_decorations);
```
or
```
dylib lib("foo.lib", dylib::use_filename_verbatim);
```
(whichever of these identifiers you like best.) Otherwise, the reader has to guess what `false` means. This breaks the [Principle of Least Astonishment](https://wiki.c2.com/?PrincipleOfLeastAstonishment).

and similarly
```
dylib lib("foo", dylib::with_os_decorations);
```
if I want to.

**Comment by martin-olivier** [comment]
Hello Eyal,
I've made your request changes on https://github.com/martin-olivier/dylib/pull/52
Feel free to review those changes
