### ISSUE TITLE
Publish to conan / vcpkg

### ISSUE THREAD

**Issue by innerlee** [martin-olivier/dylib#60]
### Description

Thanks for the great package. Conan center holds many c++ libraries. https://conan.io/center/ It will be great to publish this package there.

**Comment by CorrM** [comment]
Also, [vcpkg](https://vcpkg.io/en/packages) is worth adding to

**Comment by martin-olivier** [comment]
I have opened a PR on `vcpkg` to add `dylib`

https://github.com/microsoft/vcpkg/pull/34578

**Comment by martin-olivier** [comment]
Hello @CorrM,

`dylib` has been added on `vcpkg` master branch:
https://github.com/microsoft/vcpkg/tree/master/ports/dylib

I have also added a section on the documentation to explain how to install and use `dylib` with `vcpkg`:
https://github.com/martin-olivier/dylib#vcpkg

**Comment by CorrM** [comment]
Thanks for your time!, now its more ez to manage dylib as a dependency <3

**Comment by martin-olivier** [comment]
Hello @innerlee,

I have opened a PR on `conan-center` to add `dylib`

https://github.com/conan-io/conan-center-index/pull/20803

**Comment by martin-olivier** [comment]
Hello @innerlee,

`dylib` has been added on `conan-center` master branch:
https://github.com/conan-io/conan-center-index/tree/master/recipes/dylib

I have also added a section on the documentation to explain how to install and use `dylib` with `conan`:
https://github.com/martin-olivier/dylib#using-a-package-manager
