### ISSUE TITLE
The packaging via CPack was gone

### ISSUE THREAD

**Issue by KOLANICH** [martin-olivier/dylib#69]
The packaging via CPack was gone in 3c748b832d205bab19b0994d288a9a659aa6d996 without any words about it, but `fix: CMakeLists.txt`. It is unclear if it got gone intentionally or accidentally.

**Comment by martin-olivier** [comment]
Hello, @KOLANICH, sorry for the late response.
Back at the time, I didn't knew how to use CPack, and to be sure that this does not cause security problems, I preferred to remove it.

Since I know to use it a bit now, fell free to provide a PR to restore CPack for this project.

**Comment by martin-olivier** [comment]
I have restored CPack support on the following branch:

https://github.com/martin-olivier/dylib/tree/69-the-packaging-via-cpack-was-gone
